rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/springfield /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/caymanislands /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/kampala /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/kyiv /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/philadelphia /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/denver /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/rome /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/losangeles /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/worcester /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/gaborone /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/dubai /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/lagos /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/chicago /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/wellington /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/copenhagen /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/mumbai /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/sanfrancisco /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/houston /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/singapore /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/tokyo /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/capetown /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/seoul /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/miami /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/munich /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/delhi /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/sydney /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/berlin /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/johannesburg /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/athens /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/pittsfield /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
rsync -a /air_group/geog_pyloo/08_GSV/data/gsv_rgb/brussels /lustre1/g/geog_pyloo/05_timemachine/GSV/gsv_rgb/
